services:  
  backend:
    image: suryas1/todo-backend:1.0.0
    container_name: todo_backend
    restart: unless-stopped
    environment:
      JWT_SECRET: SUPER_SECRET
      DB_TYPE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: 
      DB_HOST: db.rbjlwpswzinzskvkqgul.supabase.co
      DB_PORT: 5432
      DB_DATABASE: postgres
    ports:
      - "3000:3000"

volumes:
  pgdata: